#pragma once

#include <QHash>
#include <QString>

#include <vector>

class QSoundEffect;

// Fire-and-forget sound effects, compiled into the binary from sounds.qrc.
//
// Effects are generated by tools/make_sounds.py rather than sampled, so the
// project carries no third-party audio.
class Sound
{
public:
    // Effect names match the WAV basenames in assets/sounds/.
    static constexpr const char* kClick = "ui_click";
    static constexpr const char* kBack = "ui_back";
    static constexpr const char* kDiscPlace = "disc_place";
    static constexpr const char* kDiscFlip = "disc_flip";
    static constexpr const char* kDig = "dig";
    static constexpr const char* kFlag = "flag";
    static constexpr const char* kBoom = "boom";
    static constexpr const char* kCardDeal = "card_deal";
    static constexpr const char* kCardPlace = "card_place";
    static constexpr const char* kShuffle = "shuffle";
    static constexpr const char* kBumper = "bumper";
    static constexpr const char* kSlingshot = "slingshot";
    static constexpr const char* kFlipper = "flipper";
    static constexpr const char* kLaunch = "launch";
    static constexpr const char* kDrain = "drain";
    static constexpr const char* kWin = "win";
    static constexpr const char* kLose = "lose";

    static Sound& instance();

    void play(const QString& name);

    bool muted() const { return m_muted; }
    void setMuted(bool muted);

    // 0.0 to 1.0.
    double volume() const { return m_volume; }
    void setVolume(double volume);

private:
    Sound();

    // Each effect keeps a few players in rotation: QSoundEffect restarts
    // rather than overlapping, and pinball fires the same sound in bursts.
    static constexpr int kVoices = 4;
    struct Voices {
        std::vector<QSoundEffect*> players;
        int next = 0;
    };

    QHash<QString, Voices> m_effects;
    bool m_muted = false;
    bool m_available = true;
    double m_volume = 0.5;
};
